// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateParams } from "./types/dtc/identity/v1/tx";
import { MsgCreateDidDocument } from "./types/dtc/identity/v1/tx";
import { MsgUpdateDidDocument } from "./types/dtc/identity/v1/tx";
import { MsgDeleteDidDocument } from "./types/dtc/identity/v1/tx";

import { DidDocument as typeDidDocument} from "./types"
import { Params as typeParams} from "./types"

export { MsgUpdateParams, MsgCreateDidDocument, MsgUpdateDidDocument, MsgDeleteDidDocument };

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateDidDocumentParams = {
  value: MsgCreateDidDocument,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateDidDocumentParams = {
  value: MsgUpdateDidDocument,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteDidDocumentParams = {
  value: MsgDeleteDidDocument,
  fee?: StdFee,
  memo?: string
};


type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type msgCreateDidDocumentParams = {
  value: MsgCreateDidDocument,
};

type msgUpdateDidDocumentParams = {
  value: MsgUpdateDidDocument,
};

type msgDeleteDidDocumentParams = {
  value: MsgDeleteDidDocument,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateDidDocument({ value, fee, memo }: sendMsgCreateDidDocumentParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateDidDocument: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgCreateDidDocument({ value: MsgCreateDidDocument.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateDidDocument: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateDidDocument({ value, fee, memo }: sendMsgUpdateDidDocumentParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateDidDocument: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateDidDocument({ value: MsgUpdateDidDocument.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateDidDocument: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteDidDocument({ value, fee, memo }: sendMsgDeleteDidDocumentParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteDidDocument: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgDeleteDidDocument({ value: MsgDeleteDidDocument.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteDidDocument: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/dtc.identity.v1.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		msgCreateDidDocument({ value }: msgCreateDidDocumentParams): EncodeObject {
			try {
				return { typeUrl: "/dtc.identity.v1.MsgCreateDidDocument", value: MsgCreateDidDocument.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateDidDocument: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateDidDocument({ value }: msgUpdateDidDocumentParams): EncodeObject {
			try {
				return { typeUrl: "/dtc.identity.v1.MsgUpdateDidDocument", value: MsgUpdateDidDocument.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateDidDocument: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteDidDocument({ value }: msgDeleteDidDocumentParams): EncodeObject {
			try {
				return { typeUrl: "/dtc.identity.v1.MsgDeleteDidDocument", value: MsgDeleteDidDocument.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteDidDocument: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						DidDocument: getStructure(typeDidDocument.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			DtcIdentityV_1: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;