// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dtc/identity/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19faca8396e375a, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19faca8396e375a, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGetDidDocumentRequest defines the QueryGetDidDocumentRequest message.
type QueryGetDidDocumentRequest struct {
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (m *QueryGetDidDocumentRequest) Reset()         { *m = QueryGetDidDocumentRequest{} }
func (m *QueryGetDidDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDidDocumentRequest) ProtoMessage()    {}
func (*QueryGetDidDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19faca8396e375a, []int{2}
}
func (m *QueryGetDidDocumentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDidDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDidDocumentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDidDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDidDocumentRequest.Merge(m, src)
}
func (m *QueryGetDidDocumentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDidDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDidDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDidDocumentRequest proto.InternalMessageInfo

func (m *QueryGetDidDocumentRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

// QueryGetDidDocumentResponse defines the QueryGetDidDocumentResponse message.
type QueryGetDidDocumentResponse struct {
	DidDocument DidDocument `protobuf:"bytes,1,opt,name=did_document,json=didDocument,proto3" json:"did_document"`
}

func (m *QueryGetDidDocumentResponse) Reset()         { *m = QueryGetDidDocumentResponse{} }
func (m *QueryGetDidDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDidDocumentResponse) ProtoMessage()    {}
func (*QueryGetDidDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19faca8396e375a, []int{3}
}
func (m *QueryGetDidDocumentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDidDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDidDocumentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDidDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDidDocumentResponse.Merge(m, src)
}
func (m *QueryGetDidDocumentResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDidDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDidDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDidDocumentResponse proto.InternalMessageInfo

func (m *QueryGetDidDocumentResponse) GetDidDocument() DidDocument {
	if m != nil {
		return m.DidDocument
	}
	return DidDocument{}
}

// QueryAllDidDocumentRequest defines the QueryAllDidDocumentRequest message.
type QueryAllDidDocumentRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDidDocumentRequest) Reset()         { *m = QueryAllDidDocumentRequest{} }
func (m *QueryAllDidDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDidDocumentRequest) ProtoMessage()    {}
func (*QueryAllDidDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19faca8396e375a, []int{4}
}
func (m *QueryAllDidDocumentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDidDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDidDocumentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDidDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDidDocumentRequest.Merge(m, src)
}
func (m *QueryAllDidDocumentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDidDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDidDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDidDocumentRequest proto.InternalMessageInfo

func (m *QueryAllDidDocumentRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllDidDocumentResponse defines the QueryAllDidDocumentResponse message.
type QueryAllDidDocumentResponse struct {
	DidDocument []DidDocument       `protobuf:"bytes,1,rep,name=did_document,json=didDocument,proto3" json:"did_document"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDidDocumentResponse) Reset()         { *m = QueryAllDidDocumentResponse{} }
func (m *QueryAllDidDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDidDocumentResponse) ProtoMessage()    {}
func (*QueryAllDidDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19faca8396e375a, []int{5}
}
func (m *QueryAllDidDocumentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDidDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDidDocumentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDidDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDidDocumentResponse.Merge(m, src)
}
func (m *QueryAllDidDocumentResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDidDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDidDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDidDocumentResponse proto.InternalMessageInfo

func (m *QueryAllDidDocumentResponse) GetDidDocument() []DidDocument {
	if m != nil {
		return m.DidDocument
	}
	return nil
}

func (m *QueryAllDidDocumentResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryGetDidByAddressRequest defines the QueryGetDidByAddressRequest message.
type QueryGetDidByAddressRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryGetDidByAddressRequest) Reset()         { *m = QueryGetDidByAddressRequest{} }
func (m *QueryGetDidByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDidByAddressRequest) ProtoMessage()    {}
func (*QueryGetDidByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19faca8396e375a, []int{6}
}
func (m *QueryGetDidByAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDidByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDidByAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDidByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDidByAddressRequest.Merge(m, src)
}
func (m *QueryGetDidByAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDidByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDidByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDidByAddressRequest proto.InternalMessageInfo

func (m *QueryGetDidByAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryGetDidByAddressResponse defines the QueryGetDidByAddressResponse message.
type QueryGetDidByAddressResponse struct {
	IsRegistered bool   `protobuf:"varint,1,opt,name=is_registered,json=isRegistered,proto3" json:"is_registered,omitempty"`
	Did          string `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	FaceHash     string `protobuf:"bytes,3,opt,name=face_hash,json=faceHash,proto3" json:"face_hash,omitempty"`
}

func (m *QueryGetDidByAddressResponse) Reset()         { *m = QueryGetDidByAddressResponse{} }
func (m *QueryGetDidByAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDidByAddressResponse) ProtoMessage()    {}
func (*QueryGetDidByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19faca8396e375a, []int{7}
}
func (m *QueryGetDidByAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDidByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDidByAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDidByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDidByAddressResponse.Merge(m, src)
}
func (m *QueryGetDidByAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDidByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDidByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDidByAddressResponse proto.InternalMessageInfo

func (m *QueryGetDidByAddressResponse) GetIsRegistered() bool {
	if m != nil {
		return m.IsRegistered
	}
	return false
}

func (m *QueryGetDidByAddressResponse) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *QueryGetDidByAddressResponse) GetFaceHash() string {
	if m != nil {
		return m.FaceHash
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "dtc.identity.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "dtc.identity.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetDidDocumentRequest)(nil), "dtc.identity.v1.QueryGetDidDocumentRequest")
	proto.RegisterType((*QueryGetDidDocumentResponse)(nil), "dtc.identity.v1.QueryGetDidDocumentResponse")
	proto.RegisterType((*QueryAllDidDocumentRequest)(nil), "dtc.identity.v1.QueryAllDidDocumentRequest")
	proto.RegisterType((*QueryAllDidDocumentResponse)(nil), "dtc.identity.v1.QueryAllDidDocumentResponse")
	proto.RegisterType((*QueryGetDidByAddressRequest)(nil), "dtc.identity.v1.QueryGetDidByAddressRequest")
	proto.RegisterType((*QueryGetDidByAddressResponse)(nil), "dtc.identity.v1.QueryGetDidByAddressResponse")
}

func init() { proto.RegisterFile("dtc/identity/v1/query.proto", fileDescriptor_d19faca8396e375a) }

var fileDescriptor_d19faca8396e375a = []byte{
	// 629 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xc1, 0x6b, 0x13, 0x4f,
	0x14, 0xc7, 0xb3, 0x6d, 0x7f, 0xfd, 0xb5, 0xd3, 0x6a, 0x74, 0x0c, 0x34, 0x6e, 0xe2, 0x46, 0x36,
	0x56, 0xa5, 0xb5, 0x3b, 0xa4, 0x22, 0x82, 0xb7, 0x86, 0x6a, 0x3d, 0x78, 0x68, 0xf7, 0xe8, 0x25,
	0x4c, 0x32, 0xe3, 0x66, 0x20, 0xd9, 0xd9, 0xee, 0x4c, 0x82, 0xa1, 0xf4, 0xe2, 0x5f, 0x20, 0xf4,
	0xe2, 0x3f, 0x20, 0x78, 0x11, 0xfc, 0x33, 0x7a, 0x2c, 0x08, 0xe2, 0x49, 0x24, 0x11, 0xfc, 0x37,
	0x64, 0x67, 0x27, 0x4d, 0xb2, 0xd9, 0xc6, 0xe0, 0x25, 0x4c, 0xde, 0xbe, 0xef, 0x7b, 0x9f, 0x79,
	0xef, 0xbb, 0x0b, 0x0a, 0x44, 0x36, 0x10, 0x23, 0xd4, 0x97, 0x4c, 0xf6, 0x50, 0xb7, 0x82, 0x8e,
	0x3b, 0x34, 0xec, 0x39, 0x41, 0xc8, 0x25, 0x87, 0x59, 0x22, 0x1b, 0xce, 0xf0, 0xa1, 0xd3, 0xad,
	0x98, 0x37, 0x71, 0x9b, 0xf9, 0x1c, 0xa9, 0xdf, 0x38, 0xc7, 0xdc, 0x6a, 0x70, 0xd1, 0xe6, 0x02,
	0xd5, 0xb1, 0xa0, 0xb1, 0x18, 0x75, 0x2b, 0x75, 0x2a, 0x71, 0x05, 0x05, 0xd8, 0x63, 0x3e, 0x96,
	0x8c, 0xfb, 0x3a, 0xd7, 0x4e, 0x36, 0x23, 0x8c, 0xd4, 0x08, 0x6f, 0x74, 0xda, 0xd4, 0x97, 0x3a,
	0xa7, 0x98, 0xcc, 0x09, 0x70, 0x88, 0xdb, 0x42, 0x3f, 0xcd, 0x79, 0xdc, 0xe3, 0xea, 0x88, 0xa2,
	0xd3, 0x50, 0xe3, 0x71, 0xee, 0xb5, 0x28, 0xc2, 0x01, 0x43, 0xd8, 0xf7, 0xb9, 0x54, 0x4d, 0xb5,
	0xc6, 0xce, 0x01, 0x78, 0x14, 0x71, 0x1d, 0xaa, 0x42, 0x2e, 0x3d, 0xee, 0x50, 0x21, 0xed, 0x23,
	0x70, 0x6b, 0x22, 0x2a, 0x02, 0xee, 0x0b, 0x0a, 0x9f, 0x81, 0xe5, 0xb8, 0x61, 0xde, 0xb8, 0x6b,
	0x3c, 0x5c, 0xdb, 0xdd, 0x70, 0x12, 0x33, 0x70, 0x62, 0x41, 0x75, 0xf5, 0xfc, 0x47, 0x29, 0xf3,
	0xe9, 0xf7, 0x97, 0x2d, 0xc3, 0xd5, 0x0a, 0xdb, 0x01, 0xa6, 0x2a, 0x79, 0x40, 0xe5, 0x3e, 0x23,
	0xfb, 0xfa, 0x5e, 0xba, 0x21, 0xbc, 0x01, 0x16, 0x09, 0x23, 0xaa, 0xec, 0xaa, 0x1b, 0x1d, 0x6d,
	0x02, 0x0a, 0xa9, 0xf9, 0x1a, 0xe5, 0x39, 0x58, 0x1f, 0x9f, 0x8f, 0x06, 0x2a, 0x4e, 0x01, 0x8d,
	0x69, 0xab, 0x4b, 0x11, 0x95, 0xbb, 0x46, 0x46, 0x21, 0x9b, 0x68, 0xaa, 0xbd, 0x56, 0x2b, 0x85,
	0xea, 0x05, 0x00, 0xa3, 0x35, 0xe9, 0x16, 0xf7, 0x9d, 0x78, 0xa7, 0x4e, 0xb4, 0x53, 0x27, 0x36,
	0x84, 0xde, 0xa9, 0x73, 0x88, 0x3d, 0xaa, 0xb5, 0xee, 0x98, 0xd2, 0xfe, 0x6c, 0xe8, 0xcb, 0x24,
	0xdb, 0x5c, 0x79, 0x99, 0xc5, 0x7f, 0xb8, 0x0c, 0x3c, 0x98, 0xc0, 0x5d, 0x50, 0xb8, 0x0f, 0xfe,
	0x8a, 0x1b, 0x33, 0x4c, 0xf0, 0x3e, 0x9d, 0x98, 0x7d, 0xb5, 0xb7, 0x47, 0x48, 0x48, 0xc5, 0xd0,
	0x1d, 0x30, 0x0f, 0xfe, 0xc7, 0x71, 0x44, 0x2f, 0x6c, 0xf8, 0xd7, 0x0e, 0x41, 0x31, 0x5d, 0xa8,
	0x2f, 0x5a, 0x06, 0xd7, 0x98, 0xa8, 0x85, 0xd4, 0x63, 0x42, 0xd2, 0x90, 0xc6, 0x0b, 0x5f, 0x71,
	0xd7, 0x99, 0x70, 0x2f, 0x63, 0x43, 0x2f, 0x2c, 0x5c, 0x7a, 0x01, 0x16, 0xc0, 0xea, 0x1b, 0xdc,
	0xa0, 0xb5, 0x26, 0x16, 0xcd, 0xfc, 0xa2, 0x8a, 0xaf, 0x44, 0x81, 0x97, 0x58, 0x34, 0x77, 0xbf,
	0x2d, 0x81, 0xff, 0x54, 0x53, 0x28, 0xc1, 0x72, 0xec, 0x3f, 0x58, 0x9e, 0x1a, 0xdd, 0xb4, 0xc9,
	0xcd, 0x7b, 0xb3, 0x93, 0x62, 0x64, 0xbb, 0xf4, 0xee, 0xeb, 0xaf, 0xb3, 0x85, 0xdb, 0x70, 0x03,
	0xa5, 0xbf, 0x7b, 0xf0, 0x83, 0x01, 0xae, 0x4f, 0x9a, 0x14, 0x6e, 0xa7, 0x57, 0x4e, 0xb5, 0xbe,
	0xf9, 0x68, 0xbe, 0x64, 0x8d, 0xb3, 0xad, 0x70, 0x36, 0x61, 0x19, 0xcd, 0xfa, 0x5c, 0xa0, 0x13,
	0xc2, 0xc8, 0x29, 0x3c, 0x33, 0x40, 0xf6, 0x15, 0x13, 0xf3, 0xb0, 0xa5, 0xbe, 0x00, 0x57, 0xb1,
	0xa5, 0xdb, 0xd8, 0xde, 0x54, 0x6c, 0x25, 0x78, 0x67, 0x26, 0x1b, 0xfc, 0x68, 0x80, 0x6c, 0xc2,
	0x20, 0x70, 0xe6, 0x10, 0x92, 0x06, 0x34, 0x77, 0xe6, 0xcc, 0xd6, 0x5c, 0x4f, 0x14, 0x17, 0x82,
	0x3b, 0x53, 0x5c, 0x1e, 0x95, 0xb5, 0x88, 0xad, 0xde, 0xab, 0x69, 0x0b, 0xa3, 0x13, 0x7d, 0x38,
	0xad, 0x3a, 0xe7, 0x7d, 0xcb, 0xb8, 0xe8, 0x5b, 0xc6, 0xcf, 0xbe, 0x65, 0xbc, 0x1f, 0x58, 0x99,
	0x8b, 0x81, 0x95, 0xf9, 0x3e, 0xb0, 0x32, 0xaf, 0x73, 0x51, 0x9d, 0xb7, 0xa3, 0x4a, 0xb2, 0x17,
	0x50, 0x51, 0x5f, 0x56, 0x5f, 0xd4, 0xc7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xa4, 0x53,
	0x3c, 0x36, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ListDidDocument Queries a list of DidDocument items.
	GetDidDocument(ctx context.Context, in *QueryGetDidDocumentRequest, opts ...grpc.CallOption) (*QueryGetDidDocumentResponse, error)
	// ListDidDocument defines the ListDidDocument RPC.
	ListDidDocument(ctx context.Context, in *QueryAllDidDocumentRequest, opts ...grpc.CallOption) (*QueryAllDidDocumentResponse, error)
	// GetDidByAddress Queries a list of GetDidByAddress items.
	GetDidByAddress(ctx context.Context, in *QueryGetDidByAddressRequest, opts ...grpc.CallOption) (*QueryGetDidByAddressResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/dtc.identity.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetDidDocument(ctx context.Context, in *QueryGetDidDocumentRequest, opts ...grpc.CallOption) (*QueryGetDidDocumentResponse, error) {
	out := new(QueryGetDidDocumentResponse)
	err := c.cc.Invoke(ctx, "/dtc.identity.v1.Query/GetDidDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListDidDocument(ctx context.Context, in *QueryAllDidDocumentRequest, opts ...grpc.CallOption) (*QueryAllDidDocumentResponse, error) {
	out := new(QueryAllDidDocumentResponse)
	err := c.cc.Invoke(ctx, "/dtc.identity.v1.Query/ListDidDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetDidByAddress(ctx context.Context, in *QueryGetDidByAddressRequest, opts ...grpc.CallOption) (*QueryGetDidByAddressResponse, error) {
	out := new(QueryGetDidByAddressResponse)
	err := c.cc.Invoke(ctx, "/dtc.identity.v1.Query/GetDidByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ListDidDocument Queries a list of DidDocument items.
	GetDidDocument(context.Context, *QueryGetDidDocumentRequest) (*QueryGetDidDocumentResponse, error)
	// ListDidDocument defines the ListDidDocument RPC.
	ListDidDocument(context.Context, *QueryAllDidDocumentRequest) (*QueryAllDidDocumentResponse, error)
	// GetDidByAddress Queries a list of GetDidByAddress items.
	GetDidByAddress(context.Context, *QueryGetDidByAddressRequest) (*QueryGetDidByAddressResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetDidDocument(ctx context.Context, req *QueryGetDidDocumentRequest) (*QueryGetDidDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDidDocument not implemented")
}
func (*UnimplementedQueryServer) ListDidDocument(ctx context.Context, req *QueryAllDidDocumentRequest) (*QueryAllDidDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDidDocument not implemented")
}
func (*UnimplementedQueryServer) GetDidByAddress(ctx context.Context, req *QueryGetDidByAddressRequest) (*QueryGetDidByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDidByAddress not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dtc.identity.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetDidDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDidDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDidDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dtc.identity.v1.Query/GetDidDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDidDocument(ctx, req.(*QueryGetDidDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListDidDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDidDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListDidDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dtc.identity.v1.Query/ListDidDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListDidDocument(ctx, req.(*QueryAllDidDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetDidByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDidByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDidByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dtc.identity.v1.Query/GetDidByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDidByAddress(ctx, req.(*QueryGetDidByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dtc.identity.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetDidDocument",
			Handler:    _Query_GetDidDocument_Handler,
		},
		{
			MethodName: "ListDidDocument",
			Handler:    _Query_ListDidDocument_Handler,
		},
		{
			MethodName: "GetDidByAddress",
			Handler:    _Query_GetDidByAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dtc/identity/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetDidDocumentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDidDocumentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDidDocumentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDidDocumentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDidDocumentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDidDocumentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DidDocument.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllDidDocumentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDidDocumentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDidDocumentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDidDocumentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDidDocumentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDidDocumentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DidDocument) > 0 {
		for iNdEx := len(m.DidDocument) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DidDocument[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDidByAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDidByAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDidByAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDidByAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDidByAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDidByAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FaceHash) > 0 {
		i -= len(m.FaceHash)
		copy(dAtA[i:], m.FaceHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FaceHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0x12
	}
	if m.IsRegistered {
		i--
		if m.IsRegistered {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetDidDocumentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDidDocumentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DidDocument.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllDidDocumentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDidDocumentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DidDocument) > 0 {
		for _, e := range m.DidDocument {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDidByAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDidByAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsRegistered {
		n += 2
	}
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.FaceHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDidDocumentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDidDocumentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDidDocumentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDidDocumentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDidDocumentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDidDocumentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidDocument", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DidDocument.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDidDocumentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDidDocumentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDidDocumentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDidDocumentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDidDocumentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDidDocumentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidDocument", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidDocument = append(m.DidDocument, DidDocument{})
			if err := m.DidDocument[len(m.DidDocument)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDidByAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDidByAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDidByAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDidByAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDidByAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDidByAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsRegistered", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsRegistered = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaceHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FaceHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
