// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: dtc/identity/v1/did_document.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "dtc.identity.v1";

/** DidDocument defines the DidDocument message. */
export interface DidDocument {
  did: string;
  controller: string;
  faceHash: string;
  pubkeys: string;
}

function createBaseDidDocument(): DidDocument {
  return { did: "", controller: "", faceHash: "", pubkeys: "" };
}

export const DidDocument: MessageFns<DidDocument> = {
  encode(message: DidDocument, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.did !== "") {
      writer.uint32(10).string(message.did);
    }
    if (message.controller !== "") {
      writer.uint32(18).string(message.controller);
    }
    if (message.faceHash !== "") {
      writer.uint32(26).string(message.faceHash);
    }
    if (message.pubkeys !== "") {
      writer.uint32(34).string(message.pubkeys);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DidDocument {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDidDocument();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.did = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.controller = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.faceHash = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.pubkeys = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DidDocument {
    return {
      did: isSet(object.did) ? globalThis.String(object.did) : "",
      controller: isSet(object.controller) ? globalThis.String(object.controller) : "",
      faceHash: isSet(object.faceHash) ? globalThis.String(object.faceHash) : "",
      pubkeys: isSet(object.pubkeys) ? globalThis.String(object.pubkeys) : "",
    };
  },

  toJSON(message: DidDocument): unknown {
    const obj: any = {};
    if (message.did !== "") {
      obj.did = message.did;
    }
    if (message.controller !== "") {
      obj.controller = message.controller;
    }
    if (message.faceHash !== "") {
      obj.faceHash = message.faceHash;
    }
    if (message.pubkeys !== "") {
      obj.pubkeys = message.pubkeys;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DidDocument>, I>>(base?: I): DidDocument {
    return DidDocument.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DidDocument>, I>>(object: I): DidDocument {
    const message = createBaseDidDocument();
    message.did = object.did ?? "";
    message.controller = object.controller ?? "";
    message.faceHash = object.faceHash ?? "";
    message.pubkeys = object.pubkeys ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
