// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: dtc/task/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { ClaimRecord } from "./claim_record";
import { Params } from "./params";

export const protobufPackage = "dtc.task.v1";

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

/** QueryGetClaimRecordRequest defines the QueryGetClaimRecordRequest message. */
export interface QueryGetClaimRecordRequest {
  claimHash: string;
}

/** QueryGetClaimRecordResponse defines the QueryGetClaimRecordResponse message. */
export interface QueryGetClaimRecordResponse {
  claimRecord: ClaimRecord | undefined;
}

/** QueryAllClaimRecordRequest defines the QueryAllClaimRecordRequest message. */
export interface QueryAllClaimRecordRequest {
  pagination: PageRequest | undefined;
}

/** QueryAllClaimRecordResponse defines the QueryAllClaimRecordResponse message. */
export interface QueryAllClaimRecordResponse {
  claimRecord: ClaimRecord[];
  pagination: PageResponse | undefined;
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryGetClaimRecordRequest(): QueryGetClaimRecordRequest {
  return { claimHash: "" };
}

export const QueryGetClaimRecordRequest: MessageFns<QueryGetClaimRecordRequest> = {
  encode(message: QueryGetClaimRecordRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.claimHash !== "") {
      writer.uint32(10).string(message.claimHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetClaimRecordRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetClaimRecordRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.claimHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetClaimRecordRequest {
    return {
      claimHash: isSet(object.claimHash)
        ? globalThis.String(object.claimHash)
        : isSet(object.claim_hash)
        ? globalThis.String(object.claim_hash)
        : "",
    };
  },

  toJSON(message: QueryGetClaimRecordRequest): unknown {
    const obj: any = {};
    if (message.claimHash !== "") {
      obj.claimHash = message.claimHash;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetClaimRecordRequest>, I>>(base?: I): QueryGetClaimRecordRequest {
    return QueryGetClaimRecordRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetClaimRecordRequest>, I>>(object: I): QueryGetClaimRecordRequest {
    const message = createBaseQueryGetClaimRecordRequest();
    message.claimHash = object.claimHash ?? "";
    return message;
  },
};

function createBaseQueryGetClaimRecordResponse(): QueryGetClaimRecordResponse {
  return { claimRecord: undefined };
}

export const QueryGetClaimRecordResponse: MessageFns<QueryGetClaimRecordResponse> = {
  encode(message: QueryGetClaimRecordResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.claimRecord !== undefined) {
      ClaimRecord.encode(message.claimRecord, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetClaimRecordResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetClaimRecordResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.claimRecord = ClaimRecord.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetClaimRecordResponse {
    return {
      claimRecord: isSet(object.claimRecord)
        ? ClaimRecord.fromJSON(object.claimRecord)
        : isSet(object.claim_record)
        ? ClaimRecord.fromJSON(object.claim_record)
        : undefined,
    };
  },

  toJSON(message: QueryGetClaimRecordResponse): unknown {
    const obj: any = {};
    if (message.claimRecord !== undefined) {
      obj.claimRecord = ClaimRecord.toJSON(message.claimRecord);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetClaimRecordResponse>, I>>(base?: I): QueryGetClaimRecordResponse {
    return QueryGetClaimRecordResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetClaimRecordResponse>, I>>(object: I): QueryGetClaimRecordResponse {
    const message = createBaseQueryGetClaimRecordResponse();
    message.claimRecord = (object.claimRecord !== undefined && object.claimRecord !== null)
      ? ClaimRecord.fromPartial(object.claimRecord)
      : undefined;
    return message;
  },
};

function createBaseQueryAllClaimRecordRequest(): QueryAllClaimRecordRequest {
  return { pagination: undefined };
}

export const QueryAllClaimRecordRequest: MessageFns<QueryAllClaimRecordRequest> = {
  encode(message: QueryAllClaimRecordRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllClaimRecordRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllClaimRecordRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllClaimRecordRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllClaimRecordRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllClaimRecordRequest>, I>>(base?: I): QueryAllClaimRecordRequest {
    return QueryAllClaimRecordRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllClaimRecordRequest>, I>>(object: I): QueryAllClaimRecordRequest {
    const message = createBaseQueryAllClaimRecordRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryAllClaimRecordResponse(): QueryAllClaimRecordResponse {
  return { claimRecord: [], pagination: undefined };
}

export const QueryAllClaimRecordResponse: MessageFns<QueryAllClaimRecordResponse> = {
  encode(message: QueryAllClaimRecordResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.claimRecord) {
      ClaimRecord.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllClaimRecordResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllClaimRecordResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.claimRecord.push(ClaimRecord.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllClaimRecordResponse {
    return {
      claimRecord: globalThis.Array.isArray(object?.claimRecord)
        ? object.claimRecord.map((e: any) => ClaimRecord.fromJSON(e))
        : globalThis.Array.isArray(object?.claim_record)
        ? object.claim_record.map((e: any) => ClaimRecord.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryAllClaimRecordResponse): unknown {
    const obj: any = {};
    if (message.claimRecord?.length) {
      obj.claimRecord = message.claimRecord.map((e) => ClaimRecord.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllClaimRecordResponse>, I>>(base?: I): QueryAllClaimRecordResponse {
    return QueryAllClaimRecordResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllClaimRecordResponse>, I>>(object: I): QueryAllClaimRecordResponse {
    const message = createBaseQueryAllClaimRecordResponse();
    message.claimRecord = object.claimRecord?.map((e) => ClaimRecord.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /** ListClaimRecord Queries a list of ClaimRecord items. */
  GetClaimRecord(request: QueryGetClaimRecordRequest): Promise<QueryGetClaimRecordResponse>;
  /** ListClaimRecord defines the ListClaimRecord RPC. */
  ListClaimRecord(request: QueryAllClaimRecordRequest): Promise<QueryAllClaimRecordResponse>;
}

export const QueryServiceName = "dtc.task.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.GetClaimRecord = this.GetClaimRecord.bind(this);
    this.ListClaimRecord = this.ListClaimRecord.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  GetClaimRecord(request: QueryGetClaimRecordRequest): Promise<QueryGetClaimRecordResponse> {
    const data = QueryGetClaimRecordRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetClaimRecord", data);
    return promise.then((data) => QueryGetClaimRecordResponse.decode(new BinaryReader(data)));
  }

  ListClaimRecord(request: QueryAllClaimRecordRequest): Promise<QueryAllClaimRecordResponse> {
    const data = QueryAllClaimRecordRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListClaimRecord", data);
    return promise.then((data) => QueryAllClaimRecordResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
