// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: dtc/task/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "dtc.task.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /** NOTE: All parameters must be supplied. */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgCreateClaimRecord defines the MsgCreateClaimRecord message. */
export interface MsgCreateClaimRecord {
  creator: string;
  claimHash: string;
  taskId: string;
  userId: string;
  signature: string;
}

/** MsgCreateClaimRecordResponse defines the MsgCreateClaimRecordResponse message. */
export interface MsgCreateClaimRecordResponse {
}

/** MsgUpdateClaimRecord defines the MsgUpdateClaimRecord message. */
export interface MsgUpdateClaimRecord {
  creator: string;
  claimHash: string;
  taskId: string;
  userId: string;
  signature: string;
}

/** MsgUpdateClaimRecordResponse defines the MsgUpdateClaimRecordResponse message. */
export interface MsgUpdateClaimRecordResponse {
}

/** MsgDeleteClaimRecord defines the MsgDeleteClaimRecord message. */
export interface MsgDeleteClaimRecord {
  creator: string;
  claimHash: string;
}

/** MsgDeleteClaimRecordResponse defines the MsgDeleteClaimRecordResponse message. */
export interface MsgDeleteClaimRecordResponse {
}

/** MsgClaimReward defines the MsgClaimReward message. */
export interface MsgClaimReward {
  creator: string;
  taskId: string;
  amount: string;
  signature: string;
  /** recipient 是实际接收奖金的用户地址（中台代办领奖时使用） */
  recipient: string;
}

/** MsgClaimRewardResponse defines the MsgClaimRewardResponse message. */
export interface MsgClaimRewardResponse {
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgCreateClaimRecord(): MsgCreateClaimRecord {
  return { creator: "", claimHash: "", taskId: "", userId: "", signature: "" };
}

export const MsgCreateClaimRecord: MessageFns<MsgCreateClaimRecord> = {
  encode(message: MsgCreateClaimRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.claimHash !== "") {
      writer.uint32(18).string(message.claimHash);
    }
    if (message.taskId !== "") {
      writer.uint32(26).string(message.taskId);
    }
    if (message.userId !== "") {
      writer.uint32(34).string(message.userId);
    }
    if (message.signature !== "") {
      writer.uint32(42).string(message.signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateClaimRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateClaimRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.claimHash = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.signature = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateClaimRecord {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      claimHash: isSet(object.claimHash)
        ? globalThis.String(object.claimHash)
        : isSet(object.claim_hash)
        ? globalThis.String(object.claim_hash)
        : "",
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      signature: isSet(object.signature) ? globalThis.String(object.signature) : "",
    };
  },

  toJSON(message: MsgCreateClaimRecord): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.claimHash !== "") {
      obj.claimHash = message.claimHash;
    }
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.signature !== "") {
      obj.signature = message.signature;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateClaimRecord>, I>>(base?: I): MsgCreateClaimRecord {
    return MsgCreateClaimRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateClaimRecord>, I>>(object: I): MsgCreateClaimRecord {
    const message = createBaseMsgCreateClaimRecord();
    message.creator = object.creator ?? "";
    message.claimHash = object.claimHash ?? "";
    message.taskId = object.taskId ?? "";
    message.userId = object.userId ?? "";
    message.signature = object.signature ?? "";
    return message;
  },
};

function createBaseMsgCreateClaimRecordResponse(): MsgCreateClaimRecordResponse {
  return {};
}

export const MsgCreateClaimRecordResponse: MessageFns<MsgCreateClaimRecordResponse> = {
  encode(_: MsgCreateClaimRecordResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateClaimRecordResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateClaimRecordResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgCreateClaimRecordResponse {
    return {};
  },

  toJSON(_: MsgCreateClaimRecordResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateClaimRecordResponse>, I>>(base?: I): MsgCreateClaimRecordResponse {
    return MsgCreateClaimRecordResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateClaimRecordResponse>, I>>(_: I): MsgCreateClaimRecordResponse {
    const message = createBaseMsgCreateClaimRecordResponse();
    return message;
  },
};

function createBaseMsgUpdateClaimRecord(): MsgUpdateClaimRecord {
  return { creator: "", claimHash: "", taskId: "", userId: "", signature: "" };
}

export const MsgUpdateClaimRecord: MessageFns<MsgUpdateClaimRecord> = {
  encode(message: MsgUpdateClaimRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.claimHash !== "") {
      writer.uint32(18).string(message.claimHash);
    }
    if (message.taskId !== "") {
      writer.uint32(26).string(message.taskId);
    }
    if (message.userId !== "") {
      writer.uint32(34).string(message.userId);
    }
    if (message.signature !== "") {
      writer.uint32(42).string(message.signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateClaimRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateClaimRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.claimHash = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.signature = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateClaimRecord {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      claimHash: isSet(object.claimHash)
        ? globalThis.String(object.claimHash)
        : isSet(object.claim_hash)
        ? globalThis.String(object.claim_hash)
        : "",
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      signature: isSet(object.signature) ? globalThis.String(object.signature) : "",
    };
  },

  toJSON(message: MsgUpdateClaimRecord): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.claimHash !== "") {
      obj.claimHash = message.claimHash;
    }
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.signature !== "") {
      obj.signature = message.signature;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateClaimRecord>, I>>(base?: I): MsgUpdateClaimRecord {
    return MsgUpdateClaimRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateClaimRecord>, I>>(object: I): MsgUpdateClaimRecord {
    const message = createBaseMsgUpdateClaimRecord();
    message.creator = object.creator ?? "";
    message.claimHash = object.claimHash ?? "";
    message.taskId = object.taskId ?? "";
    message.userId = object.userId ?? "";
    message.signature = object.signature ?? "";
    return message;
  },
};

function createBaseMsgUpdateClaimRecordResponse(): MsgUpdateClaimRecordResponse {
  return {};
}

export const MsgUpdateClaimRecordResponse: MessageFns<MsgUpdateClaimRecordResponse> = {
  encode(_: MsgUpdateClaimRecordResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateClaimRecordResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateClaimRecordResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateClaimRecordResponse {
    return {};
  },

  toJSON(_: MsgUpdateClaimRecordResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateClaimRecordResponse>, I>>(base?: I): MsgUpdateClaimRecordResponse {
    return MsgUpdateClaimRecordResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateClaimRecordResponse>, I>>(_: I): MsgUpdateClaimRecordResponse {
    const message = createBaseMsgUpdateClaimRecordResponse();
    return message;
  },
};

function createBaseMsgDeleteClaimRecord(): MsgDeleteClaimRecord {
  return { creator: "", claimHash: "" };
}

export const MsgDeleteClaimRecord: MessageFns<MsgDeleteClaimRecord> = {
  encode(message: MsgDeleteClaimRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.claimHash !== "") {
      writer.uint32(18).string(message.claimHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteClaimRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDeleteClaimRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.claimHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgDeleteClaimRecord {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      claimHash: isSet(object.claimHash)
        ? globalThis.String(object.claimHash)
        : isSet(object.claim_hash)
        ? globalThis.String(object.claim_hash)
        : "",
    };
  },

  toJSON(message: MsgDeleteClaimRecord): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.claimHash !== "") {
      obj.claimHash = message.claimHash;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDeleteClaimRecord>, I>>(base?: I): MsgDeleteClaimRecord {
    return MsgDeleteClaimRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDeleteClaimRecord>, I>>(object: I): MsgDeleteClaimRecord {
    const message = createBaseMsgDeleteClaimRecord();
    message.creator = object.creator ?? "";
    message.claimHash = object.claimHash ?? "";
    return message;
  },
};

function createBaseMsgDeleteClaimRecordResponse(): MsgDeleteClaimRecordResponse {
  return {};
}

export const MsgDeleteClaimRecordResponse: MessageFns<MsgDeleteClaimRecordResponse> = {
  encode(_: MsgDeleteClaimRecordResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteClaimRecordResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDeleteClaimRecordResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgDeleteClaimRecordResponse {
    return {};
  },

  toJSON(_: MsgDeleteClaimRecordResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDeleteClaimRecordResponse>, I>>(base?: I): MsgDeleteClaimRecordResponse {
    return MsgDeleteClaimRecordResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDeleteClaimRecordResponse>, I>>(_: I): MsgDeleteClaimRecordResponse {
    const message = createBaseMsgDeleteClaimRecordResponse();
    return message;
  },
};

function createBaseMsgClaimReward(): MsgClaimReward {
  return { creator: "", taskId: "", amount: "", signature: "", recipient: "" };
}

export const MsgClaimReward: MessageFns<MsgClaimReward> = {
  encode(message: MsgClaimReward, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.taskId !== "") {
      writer.uint32(18).string(message.taskId);
    }
    if (message.amount !== "") {
      writer.uint32(26).string(message.amount);
    }
    if (message.signature !== "") {
      writer.uint32(34).string(message.signature);
    }
    if (message.recipient !== "") {
      writer.uint32(42).string(message.recipient);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgClaimReward {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgClaimReward();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.signature = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.recipient = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgClaimReward {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      signature: isSet(object.signature) ? globalThis.String(object.signature) : "",
      recipient: isSet(object.recipient) ? globalThis.String(object.recipient) : "",
    };
  },

  toJSON(message: MsgClaimReward): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.signature !== "") {
      obj.signature = message.signature;
    }
    if (message.recipient !== "") {
      obj.recipient = message.recipient;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgClaimReward>, I>>(base?: I): MsgClaimReward {
    return MsgClaimReward.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgClaimReward>, I>>(object: I): MsgClaimReward {
    const message = createBaseMsgClaimReward();
    message.creator = object.creator ?? "";
    message.taskId = object.taskId ?? "";
    message.amount = object.amount ?? "";
    message.signature = object.signature ?? "";
    message.recipient = object.recipient ?? "";
    return message;
  },
};

function createBaseMsgClaimRewardResponse(): MsgClaimRewardResponse {
  return {};
}

export const MsgClaimRewardResponse: MessageFns<MsgClaimRewardResponse> = {
  encode(_: MsgClaimRewardResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgClaimRewardResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgClaimRewardResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgClaimRewardResponse {
    return {};
  },

  toJSON(_: MsgClaimRewardResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgClaimRewardResponse>, I>>(base?: I): MsgClaimRewardResponse {
    return MsgClaimRewardResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgClaimRewardResponse>, I>>(_: I): MsgClaimRewardResponse {
    const message = createBaseMsgClaimRewardResponse();
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** CreateClaimRecord defines the CreateClaimRecord RPC. */
  CreateClaimRecord(request: MsgCreateClaimRecord): Promise<MsgCreateClaimRecordResponse>;
  /** UpdateClaimRecord defines the UpdateClaimRecord RPC. */
  UpdateClaimRecord(request: MsgUpdateClaimRecord): Promise<MsgUpdateClaimRecordResponse>;
  /** DeleteClaimRecord defines the DeleteClaimRecord RPC. */
  DeleteClaimRecord(request: MsgDeleteClaimRecord): Promise<MsgDeleteClaimRecordResponse>;
  /** ClaimReward defines the ClaimReward RPC. */
  ClaimReward(request: MsgClaimReward): Promise<MsgClaimRewardResponse>;
}

export const MsgServiceName = "dtc.task.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.CreateClaimRecord = this.CreateClaimRecord.bind(this);
    this.UpdateClaimRecord = this.UpdateClaimRecord.bind(this);
    this.DeleteClaimRecord = this.DeleteClaimRecord.bind(this);
    this.ClaimReward = this.ClaimReward.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  CreateClaimRecord(request: MsgCreateClaimRecord): Promise<MsgCreateClaimRecordResponse> {
    const data = MsgCreateClaimRecord.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateClaimRecord", data);
    return promise.then((data) => MsgCreateClaimRecordResponse.decode(new BinaryReader(data)));
  }

  UpdateClaimRecord(request: MsgUpdateClaimRecord): Promise<MsgUpdateClaimRecordResponse> {
    const data = MsgUpdateClaimRecord.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateClaimRecord", data);
    return promise.then((data) => MsgUpdateClaimRecordResponse.decode(new BinaryReader(data)));
  }

  DeleteClaimRecord(request: MsgDeleteClaimRecord): Promise<MsgDeleteClaimRecordResponse> {
    const data = MsgDeleteClaimRecord.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteClaimRecord", data);
    return promise.then((data) => MsgDeleteClaimRecordResponse.decode(new BinaryReader(data)));
  }

  ClaimReward(request: MsgClaimReward): Promise<MsgClaimRewardResponse> {
    const data = MsgClaimReward.encode(request).finish();
    const promise = this.rpc.request(this.service, "ClaimReward", data);
    return promise.then((data) => MsgClaimRewardResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
